name: frankn
description: "Client for Frankn"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_webrtc: ^1.3.0
  web_socket: ^1.0.1
  web_socket_channel: ^3.0.3
  uuid: ^4.5.2
  json_annotation: ^4.9.0
  crypto: ^3.0.7
  hex: ^0.2.0
  argon2: ^1.0.1
  pointycastle: ^3.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_foreground_task: ^9.2.0
  volume_controller: ^3.4.1
  file_picker: ^10.3.8
  awesome_notifications: ^0.11.0
  audio_service: ^0.18.18
  just_audio: ^0.10.5
  dartssh2: ^2.13.0
  xterm: ^4.0.0
  device_info_plus: ^12.3.0
  open_filex: ^4.7.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  re_editor:
    git:
      url: https://github.com/Kindness-Kismet/re-editor
      ref: 10fdbc13ac96600f63ea16cebda5799771bdb898
  re_highlight: ^0.0.3
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  mobile_scanner: ^7.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^8.0.2
  flutter_markdown: ^0.7.7+1
  flutter_highlighter: ^0.1.1
  markdown: ^7.3.1
  flutter_math_fork: ^0.7.4
  flutter_markdown_latex: ^0.3.4
  image_picker: ^1.2.2
  convert: ^3.1.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: JetBrainsMonoNerdFont
      fonts:
        - asset: assets/fonts/JetBrainsMonoNerdFont-Regular.ttf

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/frankn_master.png"
  adaptive_icon_background: "assets/logo/frankn_background.png"
  adaptive_icon_foreground: "assets/logo/frankn_foreground.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/frankn_master.png"
    background_color: "#1a1a1a"
    theme_color: "#1a1a1a"
  windows:
    generate: true
    image_path: "assets/logo/frankn_master.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/frankn_master.png"
  linux:
    generate: true
    image_path: "assets/logo/frankn_master.png"

